#!/bin/bash -l
# Dummy script generated by esm-tools, to be removed later: 
set -e
module purge
module load slurm
module load HLRNenv
module load sw.skl
module load cmake
module load cdo nco
module load git
module load intel/19.0.5
module load impi/2019.5
module load netcdf/intel/4.7.3

export LC_ALL=en_US.UTF-8
export FC=mpiifort
export F77=mpiifort
export MPIFC=mpiifort
export FCFLAGS=-free
export CC=mpiicc
export CXX=mpiicpc
export MPIROOT="$(mpiifort -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpiifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export NETCDF_DIR=/sw/dataformats/netcdf/intel.18/4.7.3/skl/
export LD_LIBRARY_PATH=$NETCDF_DIR/lib/:$LD_LIBRARY_PATH
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDF_DIR/include
export NETCDF_CXX_LIBRARIES=$NETCDF_DIR/lib
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


cd fesom-1.4
mkdir -p build; cd build; cmake ..;   make install
cd ..
