comp:
        actual:
                files:
                    - "bin/fesom.x"
                    - "bin/echam6"
        check: {}
run:
        actual:
                errors:
                    - "MISSING FILES"
                    - "Coupling var not found"
                files:
                    - "restart/echam/restart*.nc*"
                    - "restart/fesom/fesom.*.oce.restart.nc*"
                    - "restart/fesom/fesom.*.ice.restart.nc*"
                    - "outdata/echam/*"
                    # no daily output - "outdata/fesom/*.fesom.*.nc"
        check: {}

ignore_compare:
    awiesm-2.1_icebergs:
        finished_config:
            # Icebergs ignored lines
            - "iceberg_dir: /home/ollie/lackerma/ICEBERGS/ib_10000/"
            - "iceberg_dir: <HOME_DIR>/esm_tools/configs//../src/esm_tests/resources/runscripts/awiesm/run_files4check_runs/awiesm-2.1_icebergs/"
            - "height: <HOME_DIR>/esm_tools/configs//../src/esm_tests/resources/runscripts/awiesm/run_files4check_runs/awiesm-2.1_icebergs//HEIGHT.dat"
            - "latitude: <HOME_DIR>/esm_tools/configs//../src/esm_tests/resources/runscripts/awiesm/run_files4check_runs/awiesm-2.1_icebergs//LAT.dat"
            - "length: <HOME_DIR>/esm_tools/configs//../src/esm_tests/resources/runscripts/awiesm/run_files4check_runs/awiesm-2.1_icebergs//LENGTH.dat"
            - "longitude: <HOME_DIR>/esm_tools/configs//../src/esm_tests/resources/runscripts/awiesm/run_files4check_runs/awiesm-2.1_icebergs//LON.dat"
            - "scaling: /home/ollie/lackerma/ICEBERGS/ib_10000//SCALING.dat"
            - "scaling: <HOME_DIR>/esm_tools/configs//../src/esm_tests/resources/runscripts/awiesm/run_files4check_runs/awiesm-2.1_icebergs//SCALING.dat"
            - "height: /home/ollie/lackerma/ICEBERGS/ib_10000//HEIGHT.dat"
            - "latitude: /home/ollie/lackerma/ICEBERGS/ib_10000//LAT.dat"
            - "length: /home/ollie/lackerma/ICEBERGS/ib_10000//LENGTH.dat"
            - "longitude: /home/ollie/lackerma/ICEBERGS/ib_10000//LON.dat"
#    all: # ignore for all in this folder
#        finished_config
#            - "a str"

computers:
        - ollie
        - mistral
        - levante
