#!/bin/bash
#SBATCH --partition=compute
#SBATCH --time=00:10:00
#SBATCH --ntasks=1
#SBATCH --output=<TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/log/icon-2025.10-fesom-pictl-r2b5-core2_icon-fesom_Tripy_Fesom_18500101-18500101_%j.log --error=<TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/log/icon-2025.10-fesom-pictl-r2b5-core2_icon-fesom_Tripy_Fesom_18500101-18500101_%j.log
#SBATCH --job-name=icon-2025.10-fesom-pictl-r2b5-core2
#SBATCH --account=bb0519
#SBATCH --mail-type=NONE
#SBATCH --tasks-per-node=128
#SBATCH --exclusive

# Store batch system environment variables for later sourcing
declare -p | grep -E "(SLURM)" > <TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/run_18500101-18500101/work//batch_system.env

module purge
module load git/2.31.1-gcc-11.2.0
module load cdo/2.0.5-gcc-11.2.0
module load nco/5.0.6-gcc-11.2.0
module load intel-oneapi-compilers/2022.0.1-gcc-11.2.0
module load intel-oneapi-mkl/2022.0.1-gcc-11.2.0
module load openmpi/4.1.2-intel-2021.5.0
module load netcdf-c/4.8.1-openmpi-4.1.2-intel-2021.5.0
module load netcdf-fortran/4.5.3-openmpi-4.1.2-intel-2021.5.0
module load hdf5/1.12.1-openmpi-4.1.2-intel-2021.5.0

export LC_ALL=en_US.UTF-8
export CPU_MODEL=AMD_EPYC_ZEN3
export FESOM_PLATFORM_STRATEGY=levante.dkrz.de
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi2.so
export I_MPI_PMI=pmi2
export FI_PROVIDER=mlx
export I_MPI_OFI_PROVIDER=mlx
export I_MPI_FABRICS=shm:ofi
export HCOLL_ENABLE_MCAST_ALL=1
export HCOLL_MAIN_IB=mlx5_0:1
export UCX_IB_ADDR_TYPE=ib_global
export UCX_NET_DEVICES=mlx5_0:1
export UCX_TLS=shm,dc_mlx5,dc_x,self
export UCX_UNIFIED_MODE=y
export KMP_LIBRARY=turnaround
export KMP_AFFINITY=granularity=fine,scatter
export OMPI_MCA_btl=self
export OMPI_MCA_coll=^ml,hcoll
export OMPI_MCA_coll_hcoll_enable=1
export OMPI_MCA_io=romio321
export OMPI_MCA_osc=ucx
export OMPI_MCA_pml=ucx
export FC=mpif90
export F77=mpif90
export MPICC=mpicc
export MPIFC=mpif90
export CC=mpicc
export CXX=mpicxx
export MPIROOT="$(mpif90 -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpif90 -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export MPI_HOME=$MPIROOT
export MPI_ROOT=$MPIROOT
export mpi_ROOT=$MPIROOT
export MPI_DIR=$MPIROOT
export mpi_DIR=$MPIROOT
export IO_LIB_ROOT=/work/ab0246/HPC_libraries/intel-oneapi-compilers/2022.0.1-gcc-11.2.0/openmpi/4.1.2-intel-2021.5.0
export HDF5ROOT=/sw/spack-levante/hdf5-1.12.1-tvymb5
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5ROOT/include
export HDF5_ROOT=$HDF5ROOT
export NETCDFFROOT=/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NetCDF_Fortran_ROOT=$NETCDFFROOT
export NETCDF_ROOT=$NETCDFFROOT
export NETCDFROOT=/sw/spack-levante/netcdf-c-4.8.1-2k3cmu
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_LIBRARIES=$NETCDFROOT/lib
export NetCDF_C_ROOT=$NETCDFROOT
export NETCDF_PATH=$NETCDFROOT
export ECCODESROOT=$IO_LIB_ROOT
export OASIS_NETCDF=$NETCDFROOT
export OASIS_NETCDFF=$NETCDFFROOT
export PSMPIFLAGS="-lrt -lm -ldl"
export LAPACK_LIB='-mkl=sequential'
export ZLIBROOT=/usr
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export PERL5LIB=/usr/lib64/perl5
export LD_LIBRARY_PATH=$HDF5ROOT/lib:$NETCDFROOT/lib:$NETCDFFROOT/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/sw/spack-levante/intel-oneapi-mkl-2022.0.1-ttdktf/mkl/2022.0.1/lib/intel64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/sw/spack-levante/intel-oneapi-mpi-2021.5.0-mrcss7/mpi/2021.5.0/libfabric/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/run_18500101-18500101/work//lib/fesom/
export MALLOC_TRIM_THRESHOLD_=-1
export SLURM_DIST_PLANESIZE=32
export UCX_HANDLE_ERRORS=bt
export OMPI_MCA_mpi_abort_print_stack=1
export USER=<USER_ACCOUNT>
export HOME=<HOME_DIR>
export ACCOUNT=bb0519
export ESM_TESTING_DIR=<TEST_DIR>/run/icon-fesom/
export MODEL_DIR=<TEST_DIR>/comp/icon-fesom/icon-fesom-v1.0
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!
ulimit -c 0
ulimit -a
LD_LIBRARY_PATH=/sw/spack-levante/libfyaml-0.7.12-fvbhgo/lib:$LD_LIBRARY_PATH
cd <TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/run_18500101-18500101/work/
ln -sf <TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/restart/icon//icon-2025.10-fesom-pictl-r2b5-core2_restart_atm_18500101T000000Z.mfr multifile_restart_atmo.mfr
sed -i s/\'icon_/\'icon-2025.10-fesom-pictl-r2b5-core2_/ NAMELIST_*

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | Tripy_Fesom_fesom 1 1850-01-01T00:00:00 25225911 - start" >> <TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/log//icon-2025.10-fesom-pictl-r2b5-core2_icon-fesom.log

cd <TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/run_18500101-18500101/work/
time srun -l --kill-on-bad-exit=1 --hint=nomultithread --distribution=plane <TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/scripts/fesom/Subjob_tripy.sh <TEST_DIR>/run/icon-fesom//icon-2025.10-fesom-pictl-r2b5-core2/outdata/fesom/ 1850-01-01T00:00:00 1850-01-02T00:00:00 1850-01-01T00:00:00 1850-01-03T00:00:00 /pool/data/AWICM//FESOM2/MESHES_FESOM2.1//core2/ <TEST_DIR>/run/icon-fesom/ icon-2025.10-fesom-pictl-r2b5-core2 python3 True modvis.dkrz.de /var/www/projects/bb0519/<USER_ACCOUNT>/icon-2025.10-fesom-pictl-r2b5-core2 2>&1 &

wait
