#!/bin/bash -l
# Dummy script generated by esm-tools, to be removed later: 
set -e
module purge
module load git-lfs
module load perl
module load perl-uri
module load cmake
module load intel-oneapi-compilers-classic/2021.10.0
module load intel-oneapi-mpi/2021.14.0
module load intel-oneapi-mkl/2024.2.2
module load hdf5/1.14.5
module load netcdf-c/4.9.2
module load netcdf-fortran/4.5.3-hdf5-1.10
module load cdo/2.2.2-hdf5-1.10

export LC_ALL=en_US.UTF-8
export SLURM_CPU_BIND=none
export FC=mpiifort
export F77=mpiifort
export MPIFC=mpiifort
export CC=mpiicc
export CXX=mpiicpc
export MPIROOT="$(mpiifort -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpiifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export HDF5_ROOT=$HDF5_MODULE_INSTALL_PREFIX
export HDF5ROOT=$HDF5_ROOT
export NETCDF_DIR=$NETCDF_C_MODULE_INSTALL_PREFIX
export NETCDFROOT=$NETCDF_C_MODULE_INSTALL_PREFIX
export NETCDFFROOT=$NETCDF_FORTRAN_MODULE_INSTALL_PREFIX
export ECCODESROOT=/sw/rev/24.05/cascadelake_opa_rocky8/linux-rocky8-cascadelake/oneapi-2023.2.1/eccodes-2.34.0-cwlamwcpvlhsuejrpqjlr7z3pdbkkw56/
export CDOROOT=/sw/rev/24.05/cascadelake_opa_rocky8/linux-rocky8-cascadelake/oneapi-2023.2.1/cdo-2.2.2-hmzmwdifoec6niyoau7mobur43v7q52p/
export PATH=$ECCODESROOT/bin:$CDOROOT/bin:$PATH
export LD_LIBRARY_PATH=$ECCODESROOT/lib/:$ECCODESROOT/lib64/:$NETCDFROOT/lib/:$NETCDFFROOT/lib/:$HDF5ROOT/lib/:$LD_LIBRARY_PATH
export NETCDF_CXX_LIBRARIES=$NETCDF_DIR/lib
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export OASIS_NETCDF=$NETCDFROOT
export OASIS_NETCDFF=$NETCDFFROOT
export LAPACK_LIB='-qmkl=sequential'
export LAPACK_LIB_DEFAULT='-L$MKLROOT/lib/intel64 -lmkl_intel_lp64 -lmkl_core -qmkl=sequential'
export OIFS_FFTW_DIR='$MKLROOT/lib/intel64'
export OIFS_FFTW_INCLUDE='-I$OIFS_FFTW_DIR/include/'
export OIFS_FFTW_LIB='-L$OIFS_FFTW_DIR/lib/ -lmkl_intel_lp64 -lmkl_core -qmkl=sequential'
export ESM_NETCDF_C_DIR=$NETCDFROOT
export ESM_NETCDF_F_DIR=$NETCDFFROOT
export OIFS_GRIB_API_INCLUDE="-I$ECCODESROOT/include"
export OIFS_GRIB_API_LIB="-L$ECCODESROOT/lib -L$ECCODESROOT/lib64 -leccodes_f90 -leccodes"
export OIFS_GRIB_INCLUDE="$OIFS_GRIB_API_INCLUDE"
export OIFS_GRIB_LIB="$OIFS_GRIB_API_LIB"
export OIFS_GRIB_API_BIN="$ECCODESROOT/bin"
export OIFS_OASIS_BASE=$(pwd)/oasis
export OIFS_OASIS_INCLUDE="-I$OIFS_OASIS_BASE/build/lib/psmile -I$OIFS_OASIS_BASE/build/lib/psmile/scrip -I$OIFS_OASIS_BASE/build/lib/psmile/mct -I$OIFS_OASIS_BASE/build/lib/psmile/mct/mpeu"
export OIFS_OASIS_LIB="-L$OIFS_OASIS_BASE/build/lib/psmile -L$OIFS_OASIS_BASE/build/lib/psmile/scrip -L$OIFS_OASIS_BASE/build/lib/psmile/mct -L$OIFS_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"
export OIFS_NETCDF_INCLUDE="-I$NETCDFROOT/include"
export OIFS_NETCDF_LIB="-L$NETCDFROOT/lib -lnetcdf -lnetcdff"
export OIFS_NETCDFF_INCLUDE="-I$NETCDFFROOT/include"
export OIFS_NETCDFF_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export OIFS_FC=$FC
export OIFS_FFLAGS="-qopenmp -r8 -fp-model precise -align array32byte -O3 -g -traceback -xCORE_AVX2 -convert big_endian"
export OIFS_FFIXED=""
export OIFS_FCDEFS="BLAS LITTLE LINUX INTEGER_IS_INT"
export OIFS_LFLAGS="$OIFS_MPI_LIB -qopenmp"
export OIFS_CC=$CC
export OIFS_CFLAGS="-qopenmp -fp-model precise -O3 -g -traceback -xCORE_AVX2 -qopt-report=0 -std=gnu89"
export OIFS_CCDEFS="LINUX LITTLE INTEGER_IS_INT _ABI64 BLAS"
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


pushd oifs-43r3-foci30
export OIFS_TOPLEVEL_DIR=/mnt/lustre-grete/workspaces/ws/shk00060/<USER_ACCOUNT>/-esm-experiments-rzg/esm-tests/comp/focioifs/focioifs-agrif-3.0/oifs-43r3-foci30; export OIFS_XIOS=enable ; export OIFS_XIOS_DIR=/mnt/lustre-grete/workspaces/ws/shk00060/<USER_ACCOUNT>/-esm-experiments-rzg/esm-tests/comp/focioifs/focioifs-agrif-3.0/oifs-43r3-foci30/../xios ; export OIFS_XIOS_INCLUDE=-I//mnt/lustre-grete/workspaces/ws/shk00060/<USER_ACCOUNT>/-esm-experiments-rzg/esm-tests/comp/focioifs/focioifs-agrif-3.0/oifs-43r3-foci30/../xios/inc/ ; cd make; ../fcm/bin/fcm make -v -j8 -f oifs.fcm ; chmod -R 700 . ; git config core.fileMode false ; mv esm/oifs/bin/master.exe esm/oifs/bin/oifs
popd
