#!/bin/bash -l
# Dummy script generated by esm-tools, to be removed later: 
set -e
module purge
module load git-lfs
module load perl
module load perl-uri
module load cmake
module load intel-oneapi-compilers-classic/2021.10.0
module load intel-oneapi-mpi/2021.14.0
module load intel-oneapi-mkl/2024.2.2
module load hdf5/1.14.5
module load netcdf-c/4.9.2
module load netcdf-fortran/4.5.3-hdf5-1.10
module load cdo/2.2.2-hdf5-1.10

export LC_ALL=en_US.UTF-8
export SLURM_CPU_BIND=none
export FC=mpiifort
export F77=mpiifort
export MPIFC=mpiifort
export CC=mpiicc
export CXX=mpiicpc
export MPIROOT="$(mpiifort -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpiifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export HDF5_ROOT=$HDF5_MODULE_INSTALL_PREFIX
export HDF5ROOT=$HDF5_ROOT
export NETCDF_DIR=$NETCDF_C_MODULE_INSTALL_PREFIX
export NETCDFROOT=$NETCDF_C_MODULE_INSTALL_PREFIX
export NETCDFFROOT=$NETCDF_FORTRAN_MODULE_INSTALL_PREFIX
export ECCODESROOT=/sw/rev/24.05/cascadelake_opa_rocky8/linux-rocky8-cascadelake/oneapi-2023.2.1/eccodes-2.34.0-cwlamwcpvlhsuejrpqjlr7z3pdbkkw56/
export CDOROOT=/sw/rev/24.05/cascadelake_opa_rocky8/linux-rocky8-cascadelake/oneapi-2023.2.1/cdo-2.2.2-hmzmwdifoec6niyoau7mobur43v7q52p/
export PATH=$ECCODESROOT/bin:$CDOROOT/bin:$PATH
export LD_LIBRARY_PATH=$ECCODESROOT/lib/:$ECCODESROOT/lib64/:$NETCDFROOT/lib/:$NETCDFFROOT/lib/:$HDF5ROOT/lib/:$LD_LIBRARY_PATH
export NETCDF_CXX_LIBRARIES=$NETCDF_DIR/lib
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export OASIS_NETCDF=$NETCDFROOT
export OASIS_NETCDFF=$NETCDFFROOT
export RNF_OASIS_BASE=$(pwd)/oasis
export RNF_OASIS_INCLUDE="-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"
export RNF_OASIS_LIB="-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"
export RNF_NETCDF_INCLUDE="-I$NETCDFROOT/include"
export RNF_NETCDF_LIB="-L$NETCDFROOT/lib -lnetcdf"
export RNF_NETCDFF_INCLUDE="-I$NETCDFFROOT/include"
export RNF_NETCDFF_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export RNF_MPI_LIB="$MPI_LIB"
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


pushd rnfmap-agrif
rm -rf bin; mkdir bin; cd src; make ; cd .. ; cp bin/rnfmap.exe ./bin/rnfma
popd
