#!/usr/bin/bash -l
# Dummy script generated by esm-tools, to be removed later: 
set -e
module purge
module load cmake
module load intel-oneapi-compilers/2022.1.0
module load intel-oneapi-mkl/2022.1.0-gcc12.1.0
module load openmpi/4.1.3-intel2021.6.0
module load udunits/2.2.28
module load hdf5/1.12.2-openmpi4.1.3-intel2021.6.0
module load netcdf-c/4.8.1-openmpi4.1.3-intel2021.6.0
module load netcdf-fortran/4.5.4-openmpi4.1.3-intel2021.6.0
module load netcdf-cxx4/4.3.1-openmpi4.1.3-intel2021.6.0
module load eccodes/2.25.0-openmpi4.1.3-intel2021.6.0
module load cdo/2.0.5
module load nco/5.0.1
module load git/2.35.2
module load perl/5.35.0-gcc12.1.0
module load python/3.9.12
module list

export LC_ALL=en_US.UTF-8
export FC=mpif90
export F77=mpif90
export MPIFC=mpif90
export MPICC=mpicc
export CC=mpicc
export CXX=mpic++
export CPU_MODEL=AMD_EPYC_ZEN2
export FESOM_PLATFORM_STRATEGY=albedo
export PERL5LIB=/albedo/soft/sw/spack-sw/perl-uri/1.72-epj7s32/lib/perl5:/albedo/soft/sw/spack-sw/perl/5.35.0-asf6m5t/lib
export HDF5ROOT=/albedo/soft/sw/spack-sw/hdf5/1.12.2-mstdrjw/
export NETCDFROOT=/albedo/soft/sw/spack-sw/netcdf-c/4.8.1-vvxxdc3/
export NETCDFFROOT=/albedo/soft/sw/spack-sw/netcdf-fortran/4.5.4-uwfs3bu/
export ECCODESROOT=/albedo/soft/sw/spack-sw/eccodes/2.25.0-vn2k575/
export OASIS_NETCDF=$NETCDFROOT
export OASIS_NETCDFF=$NETCDFFROOT
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export MPIROOT=$(mpif90 -show | perl -lne 'm{ -I(.*?)/include } and print $1')
export MPI_LIB=$(mpif90 -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')
export LAPACK_LIB='-L/albedo/soft/sw/spack-sw/intel-oneapi-mkl/2022.1.0-akthm3n/mkl/2022.1.0 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lm -ldl'
export LD_LIBRARY_PATH=/albedo/soft/sw/spack-sw/intel-oneapi-mkl/2022.1.0-akthm3n/mkl/2022.1.0/lib/intel64:$LD_LIBRARY_PATH
export PATH=$PERL5LIB/../bin:$PATH
export PATH=$PATH:$ECCODESROOT/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/on/a/road/to/nowwhere/test/run_20000101-20001231/work//lib/fesom/
export OASIS_FFLAGS="-march=core-avx2"
export OASIS_CFLAGS="-fPIC"
export CFLAGS="-fPIC"
export CCFLAGS="-fPIC"
export FFLAGS="-fPIC"
export FCFLAGS="-fPIC"
export MKL_CBWR=AUTO,STRICT
export DATA=/on/a/road/to/nowwhere/test/run_20000101-20001231/work/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/on/a/road/to/nowwhere/test/run_20000101-20001231/work//lib/oifs/
export GRIB_SAMPLES_PATH=<TEST_DIR>/comp/awicm3/awicm3-develop/oifs-48r1/build/share/eccodes/ifs_samples/grib1_mlgrib2
export OIFS_LOGFILE=<TEST_DIR>/comp/awicm3/awicm3-develop/oifs-48r1/build/oifs_test_log.txt
export DR_HOOK_IGNORE_SIGNALS=-1
export RNF_OASIS_BASE=$(pwd)/oasis
export RNF_OASIS_INCLUDE="-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"
export RNF_OASIS_LIB="-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"
export RNF_NETCDF_INCLUDE="-I$NETCDFROOT/include"
export RNF_NETCDF_LIB="-L$NETCDFROOT/lib -lnetcdf"
export RNF_NETCDFF_INCLUDE="-I$NETCDFFROOT/include"
export RNF_NETCDFF_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export RNF_FFLAGS="-r8 -fp-model precise -align array32byte -O3 -qopenmp -g -traceback -convert big_endian -march=core-avx2 -mtune=core-avx2"
export RNF_CFLAGS="-fp-model precise -O3 -g -traceback -qopt-report=0 -fpe0 -qopenmp -march=core-avx2 -mtune=core-avx2"
export USER=<USER_ACCOUNT>
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE

unset SLURM_DISTRIBUTION
unset SLURM_NTASKS
unset SLURM_NPROCS
unset SLURM_ARBITRARY_NODELIST
unset SLURM_MEM_PER_NODE
unset SLURM_MEM_PER_CPU

pushd xios
export XIOS_TOPLEVEL=<TEST_DIR>/comp/awicm3/awicm3-develop/xios; ./make_xios --arch ESMTOOLS_levante_oasis_intel --netcdf_lib netcdf4_par --use_oasis oasis3_mct --job 24 --prod; cp bin/xios_server.exe bin/xios.x
popd
