#!/bin/bash
#SBATCH --partition=compute
#SBATCH --time=00:15:00
#SBATCH --ntasks=64
#SBATCH --output=<TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/log/foci-moz-restart-pictrl_run_foci_compute_18500101-18500101_%j.log --error=<TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/log/foci-moz-restart-pictrl_run_foci_compute_18500101-18500101_%j.log
#SBATCH --job-name=foci-moz-restart-pictrl_run
#SBATCH --account=None
#SBATCH --mail-type=NONE
#SBATCH --ntasks-per-core=1
#SBATCH --exclusive

# Store batch system environment variables for later sourcing
declare -p | grep -E "(SLURM)" > <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work//batch_system.env

module purge
module load git/2.31.1-gcc-11.2.0
module load cdo/2.0.5-gcc-11.2.0
module load nco/5.0.6-gcc-11.2.0
module load libaec/1.0.5-intel-2021.5.0
module load intel-oneapi-compilers/2022.0.1-gcc-11.2.0
module load intel-oneapi-mkl/2022.0.1-gcc-11.2.0
module load openmpi/4.1.2-intel-2021.5.0
module load netcdf-c/4.8.1-openmpi-4.1.2-intel-2021.5.0
module load netcdf-fortran/4.5.3-openmpi-4.1.2-intel-2021.5.0
module load hdf5/1.12.1-openmpi-4.1.2-intel-2021.5.0

export LC_ALL=en_US.UTF-8
export CPU_MODEL=AMD_EPYC_ZEN3
export FESOM_PLATFORM_STRATEGY=levante.dkrz.de
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi2.so
export I_MPI_PMI=pmi2
export FI_PROVIDER=mlx
export I_MPI_OFI_PROVIDER=mlx
export I_MPI_FABRICS=shm:ofi
export HCOLL_ENABLE_MCAST_ALL=1
export HCOLL_MAIN_IB=mlx5_0:1
export UCX_IB_ADDR_TYPE=ib_global
export UCX_NET_DEVICES=mlx5_0:1
export UCX_TLS=mm,knem,cma,dc_mlx5,dc_x,self
export UCX_UNIFIED_MODE=y
export KMP_LIBRARY=turnaround
export KMP_AFFINITY=granularity=fine,scatter
export OMPI_MCA_btl=self
export OMPI_MCA_coll=^ml
export OMPI_MCA_coll_hcoll_enable=1
export OMPI_MCA_io=romio321
export OMPI_MCA_osc=pt2pt
export OMPI_MCA_pml=ucx
export AEC_ROOT=/sw/spack-levante/libaec-1.0.5-gij7yv
export aec_ROOT=/sw/spack-levante/libaec-1.0.5-gij7yv
export TBBROOT=/sw/spack-levante/intel-oneapi-compilers-2022.0.1-an2cbq/tbb/2021.5.0
export TBBMALLOC_DIR=$TBBROOT/lib/intel64/gcc4.8
export FC=mpif90
export F77=mpif90
export MPICC=mpicc
export MPIFC=mpif90
export CC=mpicc
export CXX=mpicxx
export MPIROOT="$(mpif90 -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpif90 -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export MPI_HOME=$MPIROOT
export MPI_ROOT=$MPIROOT
export mpi_ROOT=$MPIROOT
export MPI_DIR=$MPIROOT
export mpi_DIR=$MPIROOT
export IO_LIB_ROOT=/work/ab0246/HPC_libraries/intel-oneapi-compilers/2022.0.1-gcc-11.2.0/openmpi/4.1.2-intel-2021.5.0
export HDF5ROOT=/sw/spack-levante/hdf5-1.12.1-tvymb5
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5ROOT/include
export HDF5_ROOT=$HDF5ROOT
export NETCDFFROOT=/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NetCDF_Fortran_ROOT=$NETCDFFROOT
export NETCDF_ROOT=$NETCDFFROOT
export NETCDFROOT=/sw/spack-levante/netcdf-c-4.8.1-2k3cmu
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_LIBRARIES=$NETCDFROOT/lib
export NetCDF_C_ROOT=$NETCDFROOT
export NETCDF_PATH=$NETCDFROOT
export ECCODESROOT=$IO_LIB_ROOT
export OASIS_NETCDF=$NETCDFROOT
export OASIS_NETCDFF=$NETCDFFROOT
export PSMPIFLAGS="-lrt -lm -ldl"
export LAPACK_LIB='-mkl=sequential'
export ZLIBROOT=/usr
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export PERL5LIB=/usr/lib64/perl5
export LD_LIBRARY_PATH=$HDF5ROOT/lib:$NETCDFROOT/lib:$NETCDFFROOT/lib:$AEC_ROOT/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/sw/spack-levante/intel-oneapi-mkl-2022.0.1-ttdktf/mkl/2022.0.1/lib/intel64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/sw/spack-levante/intel-oneapi-mpi-2021.5.0-mrcss7/mpi/2021.5.0/libfabric/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=<TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work//lib/oasis/:$LD_LIBRARY_PATH
export ACCOUNT=None
export ESM_TESTING_DIR=<TEST_DIR>/run/foci/
export MODEL_DIR=<TEST_DIR>/comp/foci/foci-moz
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 1850-01-01T00:00:00 1451 - start" >> <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/log//foci-moz-restart-pictrl_run_foci.log

cd <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work/
time srun -l --cpu-bind=cores --distribution=cyclic:cyclic --hint=nomultithread --multi-prog hostfile_srun 2>&1 &

# Call to esm_runscript to start subjobs:
# ['tidy']
process=$!

# Recover batch system environment variables
source <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work//batch_system.env; rm <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work//batch_system.env

# Comment the following line if you don't want esm_runscripts to restart:
cd <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/scripts/
esm_runscripts foci-moz-restart-pictrl_run.yaml -e foci-moz-restart-pictrl_run -t observe_compute -p ${process} -s 18500101 -r 1 -v --last-jobtype prepcompute --open-run

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 1850-01-01T00:00:00 1451 - done" >> <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/log//foci-moz-restart-pictrl_run_foci.log

wait
