#!/bin/sh -l
# Dummy script generated by esm-tools, to be removed later: 
set -e
module unload craype
module load craype/2.6.2
module load PrgEnv-cray/6.0.4
module load pbs
module load cray-mpich/7.7.3
module load craype-x86-skylake
module load cmake/3.14.0
module load cray-hdf5-parallel/1.10.2.0
module load cray-netcdf-hdf5parallel/4.6.1.3
module load cdo/1.9.5
module load fftw/2.1.5.9
module load nco/4.9.4
module load proj4/5.1.0
module load python/3.9.1
module list

export LC_ALL=en_US.UTF-8
export HDF5ROOT=$HDF5_ROOT
export NETCDFFROOT=$NETCDF_DIR
export NETCDFROOT=$NETCDF_DIR
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_LIBRARIES=$NETCDFROOT/lib
export OASIS_NETCDF=$NETCDF_DIR
export OASIS_NETCDFF=$NETCDF_DIR
export PERL5LIB=/usr/lib64/perl5
export XML2ROOT=/usr
export ZLIBROOT=/usr
export TMPDIR=/tmp
export PMI_LABEL_ERROUT=1
export ECCODESROOT=/proj/awiiccp/software/ecmwf/eccodes_cce_mpich
export MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_CRAY_OPT_THREAD_SYNC=0
export MPICH_OPT_THREAD_SYNC=0
export ENABLE_ALEPH_CRAYMPICH_WORKAROUNDS=
export FC=ftn
export CC=cc
export CXX=CC
export CRAYPE_LINK_TYPE=dynamic
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/on/a/road/to/nowwhere/test/run_20000101-20001231/work//lib/fesom/
export OASIS_FFLAGS='-emf'
export OASIS_CFLAGS="-fPIC"
export CFLAGS="-fPIC"
export CCFLAGS="-fPIC"
export FFLAGS="-fPIC"
export FCFLAGS="-fPIC"
export MKL_CBWR=AUTO,STRICT
export DATA=/on/a/road/to/nowwhere/test/run_20000101-20001231/work/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/on/a/road/to/nowwhere/test/run_20000101-20001231/work//lib/oifs/
export GRIB_SAMPLES_PATH=<TEST_DIR>comp/awicm3/awicm3-develop/oifs-48r1/build/share/eccodes/ifs_samples/grib1_mlgrib2
export OIFS_LOGFILE=<TEST_DIR>comp/awicm3/awicm3-develop/oifs-48r1/build/oifs_test_log.txt
export DR_HOOK_IGNORE_SIGNALS=-1
export RNF_OASIS_BASE=$(pwd)/oasis
export RNF_OASIS_INCLUDE="-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"
export RNF_OASIS_LIB="-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"
export RNF_NETCDF_INCLUDE=-I$NETCDF_DIR/include
export RNF_NETCDF_LIB="-L$NETCDF_DIR/lib -lnetcdf"
export RNF_NETCDFF_INCLUDE=-I$NETCDF_DIR/include
export RNF_NETCDFF_LIB="-L$NETCDF_DIR/lib -lnetcdff"
export RNF_FC=ftn
export RNF_FFLAGS="-O2 -emf -hthread1 -hflex_mp=conservative -hfp1 -hadd_paren -hbyteswapio -J./ -hcpu=x86-skylake -U_CRAYFTN"
export RNF_CFLAGS="-emf -O2 -hcpu=x86-skylake"
export USER=<USER_ACCOUNT>
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


pushd rnfmap
rm -rf bin; mkdir bin; cd src; make ; cd .. ; cp bin/rnfmap.exe ./bin/rnfma
popd
