#!/usr/bin/bash
#SBATCH --partition=batch
#SBATCH --time=00:20:00
#SBATCH --nodes=10
#SBATCH --output=<TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/log/awicm3-v3.4-TCO95L91-CORE2_initial_awicm3_compute_20000101-20000101_%j.log --error=<TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/log/awicm3-v3.4-TCO95L91-CORE2_initial_awicm3_compute_20000101-20000101_%j.log
#SBATCH --job-name=awicm3-v3.4-TCO95L91-CORE2_initial
#SBATCH --account=None
#SBATCH --mail-type=NONE
#SBATCH --exclusive

# Store batch system environment variables for later sourcing
declare -p | grep -E "(SLURM)" > <TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/run_20000101-20000101/work//batch_system.env

module use $OTHERSTAGES
module load Stages/2024
module load GCC
module load OpenMPI
module load CMake
module load Python
module load imkl
module load Perl
module load git
module load libaec FFTW cURL netCDF netCDF-Fortran ecCodes CDO NCO
module list

export LC_ALL=en_US.UTF-8
export TMPDIR=/tmp
export FC=mpifort
export F77=mpifort
export MPIFC=mpifort
export FCFLAGS=-free
export CC=mpicc
export CXX=mpic++
export MPIROOT="$($FC -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$($FC -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export AEC_ROOT=$EBROOTLIBAEC
export SZIPROOT=$EBROOTLIBAEC
export HDF5ROOT=$EBROOTHDF5
export HDF5_ROOT=$EBROOTHDF5
export NETCDFROOT=$EBROOTNETCDF
export NETCDFFROOT=$EBROOTNETCDFMINFORTRAN
export ECCODESROOT=$EBROOTECCODES
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export PERL5LIB=/p/project/chhb19/HPC_libraries/perl5/lib/perl5
export PERL5_PATH=$PERL5LIB
export PERL5OPT=-Mwarnings=FATAL,uninitialized
export MKL_CBWR=AUTO,STRICT
export LD_RUN_PATH=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/run_20000101-20000101/work//lib/fesom/
export DATA=<TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/run_20000101-20000101/work/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/run_20000101-20000101/work//lib/oifs/
export GRIB_SAMPLES_PATH=<TEST_DIR>/comp/awicm3/awicm3-develop/oifs-48r1/build/share/eccodes/ifs_samples/grib1_mlgrib2
export OIFS_LOGFILE=<TEST_DIR>/comp/awicm3/awicm3-develop/oifs-48r1/build/oifs_test_log.txt
export DR_HOOK_IGNORE_SIGNALS=-1
export LD_LIBRARY_PATH=<TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/run_20000101-20000101/work//lib/oasis/:$LD_LIBRARY_PATH
export FESOM_USE_CPLNG="active"
export ECE_CPL_NEMO_LIM="false"
export ECE_CPL_FESOM_FESIM="true"
export ECE_AWI_CPL_FESOM="true"
export USER=<USER_ACCOUNT>
export ACCOUNT=None
export ESM_TESTING_DIR=<TEST_DIR>/run/awicm3/
export MODEL_DIR=<TEST_DIR>/comp/awicm3/awicm3-develop
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE

unset SLURM_DISTRIBUTION
unset SLURM_NTASKS
unset SLURM_NPROCS
unset SLURM_ARBITRARY_NODELIST

# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 2000-01-01T00:00:00 1000 - start" >> <TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/log//awicm3-v3.4-TCO95L91-CORE2_initial_awicm3.log

cd <TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/run_20000101-20000101/work/

#Creating hostlist for MPI + MPI&OMP heterogeneous parallel job
rm -f ./hostlist
export SLURM_HOSTFILE=<TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/run_20000101-20000101/work//hostlist
IFS=$'\n'; set -f
listnodes=($(< <( scontrol show hostnames $SLURM_JOB_NODELIST )))
unset IFS; set +f
rank=0
current_core=0
current_core_mpi=0
mpi_tasks_fesom=128
omp_threads_fesom=1
mpi_tasks_oifs=128
omp_threads_oifs=1
mpi_tasks_rnfmap=1
omp_threads_rnfmap=48
mpi_tasks_xios=4
omp_threads_xios=32
for model in fesom oifs rnfmap oasis3mct xios ;do
    eval nb_of_cores=\${mpi_tasks_${model}}
    eval nb_of_cores=$((${nb_of_cores}-1))
    for nb_proc_mpi in `seq 0 ${nb_of_cores}`; do
        (( index_host = current_core / 48 ))
        host_value=${listnodes[${index_host}]}
        (( slot =  current_core % 48 ))
        echo $host_value >> hostlist
        (( current_core = current_core + omp_threads_${model} ))
    done
done

time srun -l  --multi-prog hostfile_srun 2>&1 &

# Call to esm_runscript to start subjobs:
# ['tidy']
process=$!

# Recover batch system environment variables
source <TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/run_20000101-20000101/work//batch_system.env; rm <TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/run_20000101-20000101/work//batch_system.env
unset SLURM_HOSTFILE

# Comment the following line if you don't want esm_runscripts to restart:
cd <TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/scripts/
esm_runscripts awicm3-v3.4-TCO95L91-CORE2_initial.yaml -e awicm3-v3.4-TCO95L91-CORE2_initial -t observe_compute -p ${process} -s 20000101 -r 1 -v --last-jobtype prepcompute --open-run

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 2000-01-01T00:00:00 1000 - done" >> <TEST_DIR>/run/awicm3//awicm3-v3.4-TCO95L91-CORE2_initial/log//awicm3-v3.4-TCO95L91-CORE2_initial_awicm3.log

wait
