#!/bin/bash
#SBATCH --partition=compute
#SBATCH --time=00:30:00
#SBATCH --nodes=13
#SBATCH --output=<TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/log/awiesm3-develop-levante-TL255L91-CORE2_1d_awiesm3_compute_19000101-19000101_%j.log --error=<TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/log/awiesm3-develop-levante-TL255L91-CORE2_1d_awiesm3_compute_19000101-19000101_%j.log
#SBATCH --job-name=awiesm3-develop-levante-TL255L91-CORE2_1d
#SBATCH --account=ab0246
#SBATCH --mail-type=NONE
#SBATCH --exclusive

module purge
module load python3/2023.01-gcc-11.2.0
module load git/2.31.1-gcc-11.2.0
module load cdo/2.0.5-gcc-11.2.0
module load nco/5.0.6-gcc-11.2.0
module load intel-oneapi-mkl/2022.0.1-gcc-11.2.0
module load openmpi/4.1.2-gcc-11.2.0
module unload cdo
module load fftw/3.3.10-gcc-11.2.0
module load hdf5/1.12.1-openmpi-4.1.2-gcc-11.2.0
module load netcdf-c/4.8.1-openmpi-4.1.2-gcc-11.2.0
module load netcdf-fortran/4.5.3-openmpi-4.1.2-gcc-11.2.0
module load git/2.31.1-gcc-11.2.0
module load libaec/1.0.5-gcc-11.2.0

export LC_ALL=en_US.UTF-8
export CPU_MODEL=AMD_EPYC_ZEN3
export FESOM_PLATFORM_STRATEGY=levante.dkrz.de
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi2.so
export I_MPI_PMI=pmi2
export FI_PROVIDER=mlx
export I_MPI_OFI_PROVIDER=mlx
export I_MPI_FABRICS=shm:ofi
export HCOLL_ENABLE_MCAST_ALL=1
export HCOLL_MAIN_IB=mlx5_0:1
export UCX_IB_ADDR_TYPE=ib_global
export UCX_NET_DEVICES=mlx5_0:1
export UCX_TLS=mm,knem,cma,dc_mlx5,dc_x,self
export UCX_UNIFIED_MODE=y
export KMP_LIBRARY=turnaround
export KMP_AFFINITY=granularity=fine,scatter
export OMPI_MCA_btl=self
export OMPI_MCA_coll=^ml
export OMPI_MCA_coll_hcoll_enable=1
export OMPI_MCA_io=romio321
export OMPI_MCA_osc=pt2pt
export OMPI_MCA_pml=ucx
export FC=mpif90
export F77=mpi77
export MPICC=mpicc
export MPIFC=mpif90
export CC=mpicc
export CXX=mpic++
export MPIROOT="$(mpif90 -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpif90 -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export LD_RUN_PATH=$LD_LIBRARY_PATH
export AEC_ROOT=/sw/spack-levante/libaec-1.0.5-gij7yv
export aec_ROOT=/sw/spack-levante/libaec-1.0.5-gij7yv
export HDF5ROOT=/sw/spack-levante/hdf5-1.12.1-kxfaux
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5ROOT/include
export HDF5_ROOT=$HDF5ROOT
export NetCDF_C_ROOT=/sw/spack-levante/netcdf-c-4.8.1-6qheqr
export NetCDF_Fortran_ROOT=/sw/spack-levante/netcdf-fortran-4.5.3-jlxcfz
export NETCDF_PATH=$NetCDF_C_ROOT
export NETCDF_ROOT=$NetCDF_Fortran_ROOT
export NETCDFROOT=$NetCDF_C_ROOT
export NETCDFFROOT=$NetCDF_Fortran_ROOT
export TBBROOT=/sw/spack-levante/intel-oneapi-compilers-2022.0.1-an2cbq/tbb/2021.5.0
export TBBMALLOC_DIR=$TBBROOT/lib/intel64/gcc4.8
export MPI_HOME=/sw/spack-levante/openmpi-4.1.2-yfwe6t
export MPI_ROOT=/sw/spack-levante/openmpi-4.1.2-yfwe6t
export mpi_ROOT=/sw/spack-levante/openmpi-4.1.2-yfwe6t
export MPI_DIR=/sw/spack-levante/openmpi-4.1.2-yfwe6t
export mpi_DIR=/sw/spack-levante/openmpi-4.1.2-yfwe6t
export LD_LIBRARY_PATH=$MPI_HOME/lib:$NetCDF_C_ROOT/lib:$NetCDF_Fortran_ROOT/lib:$HDF5ROOT/lib:$AEC_ROOT/lib:$TBBMALLOC_DIR:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/sw/spack-levante/intel-oneapi-mkl-2022.0.1-ttdktf/mkl/2022.0.1/lib/intel64:$LD_LIBRARY_PATH
export OASIS_NETCDF=$NETCDF_PATH
export OASIS_NETCDFF=$NETCDF_ROOT
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/run_19000101-19000101/work//lib/fesom/
export DATA=<TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/run_19000101-19000101/work/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/run_19000101-19000101/work//lib/oifs/
export GRIB_SAMPLES_PATH=<TEST_DIR>/comp/awiesm3/awiesm3-develop/oifs-48r1/build/share/eccodes/ifs_samples/grib1_mlgrib2
export OIFS_LOGFILE=<TEST_DIR>/comp/awiesm3/awiesm3-develop/oifs-48r1/build/oifs_test_log.txt
export DR_HOOK_IGNORE_SIGNALS=-1
export OIFS_DATA_DIR=/p/project/chhb19/streffing1/input/oifs-48r1/
export MKL_CBWR=AUTO,STRICT
export LD_LIBRARY_PATH=<TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/run_19000101-19000101/work//lib/oasis/:$LD_LIBRARY_PATH
export myfortrancompiler=$FC
export mygrid=TL255
export OASIS_ANCHOR=../../../oasis
export NETCDF_C_DIR=$NETCDFROOT
export NETCDF_F_DIR=$NETCDFFROOT
export OASIS_DIR=../../../oasis/arch_ecearth/
export ACCOUNT=ab0246
export ESM_TESTING_DIR=<TEST_DIR>/run/awiesm3/
export MODEL_DIR=<TEST_DIR>/comp/awiesm3/awiesm3-develop
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE

unset SLURM_DISTRIBUTION
unset SLURM_NTASKS
unset SLURM_NPROCS
unset SLURM_ARBITRARY_NODELIST

# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 1900-01-01T00:00:00 188618 - start" >> <TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/log//awiesm3-develop-levante-TL255L91-CORE2_1d_awiesm3.log

cd <TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/run_19000101-19000101/work/

#Creating hostlist for MPI + MPI&OMP heterogeneous parallel job
rm -f ./hostlist
export SLURM_HOSTFILE=<TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/run_19000101-19000101/work//hostlist
IFS=$'\n'; set -f
listnodes=($(< <( scontrol show hostnames $SLURM_JOB_NODELIST )))
unset IFS; set +f
rank=0
current_core=0
current_core_mpi=0
mpi_tasks_fesom=256
omp_threads_fesom=1
mpi_tasks_oifs=512
omp_threads_oifs=2
mpi_tasks_rnfmap=1
omp_threads_rnfmap=128
mpi_tasks_lpj_guess=8
omp_threads_lpj_guess=8
mpi_tasks_xios=4
omp_threads_xios=32
for model in fesom oifs rnfmap lpj_guess oasis3mct xios ;do
    eval nb_of_cores=\${mpi_tasks_${model}}
    eval nb_of_cores=$((${nb_of_cores}-1))
    for nb_proc_mpi in `seq 0 ${nb_of_cores}`; do
        (( index_host = current_core / 128 ))
        host_value=${listnodes[${index_host}]}
        (( slot =  current_core % 128 ))
        echo $host_value >> hostlist
        (( current_core = current_core + omp_threads_${model} ))
    done
done

time srun -l --hint=nomultithread --multi-prog hostfile_srun 2>&1 &

# Call to esm_runscript to start subjobs:
# ['tidy']
process=$! 
# Comment the following line if you don't want esm_runscripts to restart:
cd <TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/scripts/
esm_runscripts awiesm3-develop-levante-TL255L91-CORE2_1d.yaml -e awiesm3-develop-levante-TL255L91-CORE2_1d -t observe_compute -p ${process} -s 19000101 -r 1 -v --last-jobtype prepcompute --open-run

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 1900-01-01T00:00:00 188618 - done" >> <TEST_DIR>/run/awiesm3//awiesm3-develop-levante-TL255L91-CORE2_1d/log//awiesm3-develop-levante-TL255L91-CORE2_1d_awiesm3.log

wait
