#!/usr/bin/bash -l
# Dummy script generated by esm-tools, to be removed later: 
set -e
module use $OTHERSTAGES
module load Stages/2023
module load GCC/11.3.0
module load OpenMPI/4.1.4
module load CMake/3.26.3
module load Python/3.10.4
module load imkl/2022.1.0
module load Perl/5.34.1
module load git
module load libaec FFTW cURL netCDF netCDF-Fortran ecCodes CDO NCO
module list

export LC_ALL=en_US.UTF-8
export TMPDIR=/tmp
export FC=mpifort
export F77=mpifort
export MPIFC=mpifort
export FCFLAGS="-fPIC"
export CC=mpicc
export CXX=mpic++
export MPIROOT="$($FC -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$($FC -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export AEC_ROOT=$EBROOTLIBAEC
export SZIPROOT=$EBROOTLIBAEC
export HDF5ROOT=$EBROOTHDF5
export HDF5_ROOT=$EBROOTHDF5
export NETCDFROOT=$EBROOTNETCDF
export NETCDFFROOT=$EBROOTNETCDFMINFORTRAN
export ECCODESROOT=$EBROOTECCODES
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export PERL5LIB=/p/project/chhb19/HPC_libraries/perl5/lib/perl5
export PERL5_PATH=$PERL5LIB
export PERL5OPT=-Mwarnings=FATAL,uninitialized
export MKL_CBWR=AUTO,STRICT
export LD_RUN_PATH=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/on/a/road/to/nowwhere/test/run_20000101-20001231/work//lib/fesom/
export OASIS_FFLAGS="-fPIC"
export OASIS_CFLAGS="-fPIC"
export CFLAGS="-fPIC"
export CCFLAGS="-fPIC"
export FFLAGS="-fPIC"
export RNF_OASIS_BASE=$(pwd)/oasis
export RNF_OASIS_INCLUDE="-I$RNF_OASIS_BASE/build/lib/psmile -I$RNF_OASIS_BASE/build/lib/psmile/scrip -I$RNF_OASIS_BASE/build/lib/psmile/mct -I$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu"
export RNF_OASIS_LIB="-L$RNF_OASIS_BASE/build/lib/psmile -L$RNF_OASIS_BASE/build/lib/psmile/scrip -L$RNF_OASIS_BASE/build/lib/psmile/mct -L$RNF_OASIS_BASE/build/lib/psmile/mct/mpeu -lpsmile -lmct -lmpeu -lscrip"
export RNF_NETCDF_INCLUDE="-I$NETCDFROOT/include"
export RNF_NETCDF_LIB="-L$NETCDFROOT/lib -lnetcdf"
export RNF_NETCDFF_INCLUDE="-I$NETCDFFROOT/include"
export RNF_NETCDFF_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export DATA=/on/a/road/to/nowwhere/test/run_20000101-20001231/work/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/on/a/road/to/nowwhere/test/run_20000101-20001231/work//lib/oifs/
export GRIB_SAMPLES_PATH=<TEST_DIR>comp/awicm3/awicm3-develop/oifs-48r1/build/share/eccodes/ifs_samples/grib1_mlgrib2
export RNF_FFLAGS="-fdefault-real-8 -march=core-avx2 -mtune=core-avx2 -O3 -fopenmp -g -fbacktrace -fconvert=big-endian"
export OIFS_LOGFILE=<TEST_DIR>comp/awicm3/awicm3-develop/oifs-48r1/build/oifs_test_log.txt
export RNF_CFLAG="-march=core-avx2 -mtune=core-avx2 -O3 -fopenmp -g -fbacktrace -fno-opt-report -fpe0"
export DR_HOOK_IGNORE_SIGNALS=-1
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE

unset SLURM_DISTRIBUTION
unset SLURM_NTASKS
unset SLURM_NPROCS
unset SLURM_ARBITRARY_NODELIST

pushd xios
export XIOS_TOPLEVEL=<TEST_DIR>comp/awicm3/awicm3-develop/xios; ./make_xios --arch ESMTOOLS_generic_oasis_gcc --netcdf_lib netcdf4_par --use_oasis oasis3_mct --job 24 --prod; cp bin/xios_server.exe bin/xios.x
popd
