comp:
        actual:
                files:
                    - "bin/fesom*"
                    - "bin/echam6"
        check: {}
run:
        actual:
                errors:
                    - "MISSING FILES"
                files:
                    - "restart/echam/restart*.nc*"
                    - "restart/fesom/fesom.*.oce*nc*"
                    - "restart/fesom/fesom.*.ice*nc*"
                    - "outdata/echam/*"
                    - "outdata/fesom/*fesom*.nc"
        check: {}
computers:
        - ollie
        - mistral
        - levante
ignore_runscripts:
        ollie:
                - awicm1_recom_pictrl_initial.yaml
                - awicm1_recom_hist_initial.yaml
                - awicm1_recom_ssp585.yaml
