#!/bin/bash
#SBATCH --partition=standard96s
#SBATCH --time=00:15:00
#SBATCH --ntasks=64
#SBATCH --output=<TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/log/foci-moz-restart-pictrl_run_foci_compute_18500101-18500101_%j.log --error=<TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/log/foci-moz-restart-pictrl_run_foci_compute_18500101-18500101_%j.log
#SBATCH --job-name=foci-moz-restart-pictrl_run
#SBATCH --account=shk00060
#SBATCH --mail-type=NONE
#SBATCH --ntasks-per-core=1
#SBATCH --exclusive

# Store batch system environment variables for later sourcing
declare -p | grep -E "(SLURM)" > <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work//batch_system.env

module purge
module load git-lfs
module load perl
module load perl-uri
module load cmake
module load intel-oneapi-compilers-classic/2021.10.0
module load intel-oneapi-mpi/2021.14.0
module load intel-oneapi-mkl/2024.2.2
module load hdf5/1.14.5
module load netcdf-c/4.9.2
module load netcdf-fortran/4.5.3-hdf5-1.10
module load cdo/2.2.2-hdf5-1.10
source $I_MPI_ROOT/../../setvars.sh

export LC_ALL=en_US.UTF-8
export SLURM_CPU_BIND=none
export FC=mpiifort
export F77=mpiifort
export MPIFC=mpiifort
export FCFLAGS=-free
export CC=mpiicc
export CXX=mpiicpc
export MPIROOT="$(mpiifort -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpiifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export HDF5_ROOT=$HDF5_MODULE_INSTALL_PREFIX
export HDF5ROOT=$HDF5_ROOT
export NETCDF_DIR=$NETCDF_C_MODULE_INSTALL_PREFIX
export NETCDFROOT=$NETCDF_C_MODULE_INSTALL_PREFIX
export NETCDFFROOT=$NETCDF_FORTRAN_MODULE_INSTALL_PREFIX
export ECCODESROOT=/sw/rev/24.05/cascadelake_opa_rocky8/linux-rocky8-cascadelake/oneapi-2023.2.1/eccodes-2.34.0-cwlamwcpvlhsuejrpqjlr7z3pdbkkw56/
export CDOROOT=/sw/rev/24.05/cascadelake_opa_rocky8/linux-rocky8-cascadelake/oneapi-2023.2.1/cdo-2.2.2-hmzmwdifoec6niyoau7mobur43v7q52p/
export PATH=$ECCODESROOT/bin:$CDOROOT/bin:$PATH
export LD_LIBRARY_PATH=$ECCODESROOT/lib/:$ECCODESROOT/lib64/:$NETCDFROOT/lib/:$NETCDFFROOT/lib/:$HDF5ROOT/lib/:$LD_LIBRARY_PATH
export NETCDF_CXX_LIBRARIES=$NETCDF_DIR/lib
export HDF5_C_INCLUDE_DIRECTORIES=$HDF5_ROOT/include
export NETCDF_Fortran_INCLUDE_DIRECTORIES=$NETCDFFROOT/include
export NETCDF_C_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export NETCDF_CXX_INCLUDE_DIRECTORIES=$NETCDFROOT/include
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export OASIS_NETCDF=$NETCDFROOT
export OASIS_NETCDFF=$NETCDFFROOT
export LD_LIBRARY_PATH=<TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work//lib/oasis/:$LD_LIBRARY_PATH
export ECHAM6_THREADS=1
export NEMO_THREADS=1
export I_MPI_DEBUG=1
export IO_LIB_ROOT=/mnt/lustre-emmy-hdd/projects/shk00060/foci_input2/HPC_libraries
export ACCOUNT=shk00060
export ESM_TESTING_DIR=<TEST_DIR>/run/foci/
export MODEL_DIR=<TEST_DIR>/comp/foci/foci-moz
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 1850-01-01T00:00:00 999047 - start" >> <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/log//foci-moz-restart-pictrl_run_foci.log

cd <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work/
time mpirun  $(cat hostfile_srun) 2>&1 &

# Call to esm_runscript to start subjobs:
# ['tidy']
process=$!

# Recover batch system environment variables
source <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work//batch_system.env; rm <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/run_18500101-18500101/work//batch_system.env
# Activate conda environment
source /home/sebastian.wahl01/<USER_ACCOUNT>/miniforge3/bin/activate
conda activate /home/sebastian.wahl01/<USER_ACCOUNT>/miniforge3/envs/esm-tools

# Comment the following line if you don't want esm_runscripts to restart:
cd <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/scripts/
esm_runscripts foci-moz-restart-pictrl_run.yaml -e foci-moz-restart-pictrl_run -t observe_compute -p ${process} -s 18500101 -r 1 -v --last-jobtype prepcompute --open-run

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 1850-01-01T00:00:00 999047 - done" >> <TEST_DIR>/run/foci//foci-moz-restart-pictrl_run/log//foci-moz-restart-pictrl_run_foci.log

wait
