#!/bin/bash
#SBATCH --partition=compute
#SBATCH --time=00:08:00
#SBATCH --ntasks=1920
#SBATCH --output=<TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/log/icon-fesom-pictl-v2-daily_icon-fesom_compute_18500101-18500101_%j.log --error=<TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/log/icon-fesom-pictl-v2-daily_icon-fesom_compute_18500101-18500101_%j.log
#SBATCH --job-name=icon-fesom-pictl-v2-daily
#SBATCH --account=None
#SBATCH --mail-type=NONE
#SBATCH --threads-per-core=2
#SBATCH --exclusive

# Store batch system environment variables for later sourcing
declare -p | grep -E "(SLURM)" > <TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/run_18500101-18500101/work//batch_system.env

module purge
module load git/2.31.1-gcc-11.2.0
module load cdo/2.0.5-gcc-11.2.0
module load nco/5.0.6-gcc-11.2.0
module load intel-oneapi-compilers/2022.0.1-gcc-11.2.0
module load intel-oneapi-mkl/2022.0.1-gcc-11.2.0
module load openmpi/4.1.2-intel-2021.5.0

export LC_ALL=en_US.UTF-8
export CPU_MODEL=AMD_EPYC_ZEN3
export FESOM_PLATFORM_STRATEGY=levante.dkrz.de
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi2.so
export I_MPI_PMI=pmi2
export FI_PROVIDER=mlx
export I_MPI_OFI_PROVIDER=mlx
export I_MPI_FABRICS=shm:ofi
export HCOLL_ENABLE_MCAST_ALL=1
export HCOLL_MAIN_IB=mlx5_0:1
export UCX_IB_ADDR_TYPE=ib_global
export UCX_NET_DEVICES=mlx5_0:1
export UCX_TLS=shm,dc_mlx5,dc_x,self
export UCX_UNIFIED_MODE=y
export KMP_LIBRARY=turnaround
export KMP_AFFINITY=granularity=fine,scatter
export OMPI_MCA_btl=self
export OMPI_MCA_coll=^ml,hcoll
export OMPI_MCA_coll_hcoll_enable=1
export OMPI_MCA_io=romio321
export OMPI_MCA_osc=ucx
export OMPI_MCA_pml=ucx
export FC=mpif90
export F77=mpif90
export MPICC=mpicc
export MPIFC=mpif90
export CC=mpicc
export CXX=mpicxx
export MPIROOT="$(mpif90 -show | perl -lne 'm{ -I(.*?)/include } and print $1')"
export MPI_LIB="$(mpif90 -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')"
export MPI_HOME=$MPIROOT
export MPI_ROOT=$MPIROOT
export mpi_ROOT=$MPIROOT
export MPI_DIR=$MPIROOT
export mpi_DIR=$MPIROOT
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/run_18500101-18500101/work//lib/fesom/
export SLURM_DIST_PLANESIZE=8
export ICON_THREADS=1
export OMP_SCHEDULE=dynamic,1
export OMP_DYNAMIC=False
export OMP_STACKSIZE=200M
export MALLOC_TRIM_THRESHOLD_=-1
export MKL_DEBUG_CPU_TYPE=5
export MKL_ENABLE_INSTRUCTIONS=AVX2
export UCX_HANDLE_ERRORS=bt
export USER=<USER_ACCOUNT>
export HOME=/github/home
export ACCOUNT=None
export ESM_TESTING_DIR=<TEST_DIR>/run/icon-fesom/
export MODEL_DIR=<TEST_DIR>/comp/icon-fesom/icon-fesom-v2.0
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE


# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!
cd <TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/run_18500101-18500101/work/
ln -sf <TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/restart/icon//icon-fesom-pictl-v2-daily_restart_atm_18500101T000000Z.mfr multifile_restart_atmo.mfr
sed -i s/\'icon_/\'icon-fesom-pictl-v2-daily_/ NAMELIST_*

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 1850-01-01T00:00:00 1592 - start" >> <TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/log//icon-fesom-pictl-v2-daily_icon-fesom.log

cd <TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/run_18500101-18500101/work/
time srun -l --kill-on-bad-exit=1 --multi-prog hostfile_srun 2>&1 &

# Call to esm_runscript to start subjobs:
# ['tidy']
process=$!

# Recover batch system environment variables
source <TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/run_18500101-18500101/work//batch_system.env; rm <TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/run_18500101-18500101/work//batch_system.env

# Comment the following line if you don't want esm_runscripts to restart:
cd <TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/scripts/
esm_runscripts icon-fesom-pictl-v2-daily.yaml -e icon-fesom-pictl-v2-daily -t observe_compute -p ${process} -s 18500101 -r 1 -v --last-jobtype prepcompute --open-run

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | compute 1 1850-01-01T00:00:00 1592 - done" >> <TEST_DIR>/run/icon-fesom//icon-fesom-pictl-v2-daily/log//icon-fesom-pictl-v2-daily_icon-fesom.log

wait
