#!/usr/bin/bash
#SBATCH --partition=smp
#SBATCH --time=02:00:00
#SBATCH --ntasks=1
#SBATCH --output=<TEST_DIR>/run/awiesm//pi-awiesm-2.6.2/log/pi-awiesm-2.6.2_awiesm_Tripy_Fesom_18500101-18500101_%j.log --error=<TEST_DIR>/run/awiesm//pi-awiesm-2.6.2/log/pi-awiesm-2.6.2_awiesm_Tripy_Fesom_18500101-18500101_%j.log
#SBATCH --job-name=pi-awiesm-2.6.2
#SBATCH --account=computing.computing
#SBATCH --mail-type=NONE
#SBATCH --qos=12h
#SBATCH --comment='no-switch-enforce'
#SBATCH --exclusive

# Store batch system environment variables for later sourcing
declare -p | grep -E "(SLURM)" > <TEST_DIR>/run/awiesm//pi-awiesm-2.6.2/run_18500101-18500101/work//batch_system.env

module purge
module load cmake
module load intel-oneapi-compilers/2022.1.0
module load intel-oneapi-mkl/2022.1.0-gcc12.1.0
module load openmpi/4.1.3-intel2021.6.0
module load udunits/2.2.28
module load hdf5/1.12.2-openmpi4.1.3-intel2021.6.0
module load netcdf-c/4.8.1-openmpi4.1.3-intel2021.6.0
module load netcdf-fortran/4.5.4-openmpi4.1.3-intel2021.6.0
module load netcdf-cxx4/4.3.1-openmpi4.1.3-intel2021.6.0
module load eccodes/2.25.0-openmpi4.1.3-intel2021.6.0
module load libaec/1.0.6-intel2021.6.0
module load cdo/2.0.5
module load nco/5.0.1
module load git/2.35.2
module load perl/5.35.0-gcc12.1.0
module list

export LC_ALL=en_US.UTF-8
export FC=mpif90
export F77=mpif90
export MPIFC=mpif90
export MPICC=mpicc
export CC=mpicc
export CXX=mpic++
export CPU_MODEL=AMD_EPYC_ZEN2
export FESOM_PLATFORM_STRATEGY=albedo
export PERL5LIB=/albedo/soft/sw/spack-sw/perl-uri/1.72-epj7s32/lib/perl5:/albedo/soft/sw/spack-sw/perl/5.35.0-asf6m5t/lib
export HDF5ROOT=/albedo/soft/sw/spack-sw/hdf5/1.12.2-mstdrjw/
export NETCDFROOT=/albedo/soft/sw/spack-sw/netcdf-c/4.8.1-vvxxdc3/
export NETCDFFROOT=/albedo/soft/sw/spack-sw/netcdf-fortran/4.5.4-uwfs3bu/
export ECCODESROOT=/albedo/soft/sw/spack-sw/eccodes/2.25.0-vn2k575/
export OASIS_NETCDF=$NETCDFROOT
export OASIS_NETCDFF=$NETCDFFROOT
export OASIS3MCT_FC_LIB="-L$NETCDFFROOT/lib -lnetcdff"
export MPIROOT=$(mpif90 -show | perl -lne 'm{ -I(.*?)/include } and print $1')
export MPI_LIB=$(mpif90 -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')
export OMPI_MCA_io=romio321
export LAPACK_LIB='-L/albedo/soft/sw/spack-sw/intel-oneapi-mkl/2022.1.0-akthm3n/mkl/2022.1.0 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lm -ldl'
export TBBROOT=/albedo/soft/sw/spack-sw/intel-oneapi-mkl/2022.1.0-akthm3n/tbb/latest
export LD_LIBRARY_PATH=$HDF5ROOT/lib:$NETCDFROOT/lib:$NETCDFFROOT/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/albedo/soft/sw/spack-sw/intel-oneapi-mkl/2022.1.0-akthm3n/mkl/2022.1.0/lib/intel64:/albedo/soft/sw/spack-sw/intel-oneapi-mkl/2022.1.0-akthm3n/tbb/latest/lib/intel64/gcc4.8:$LD_LIBRARY_PATH
export PATH=$PERL5LIB/../bin:$PATH
export PATH=$PATH:$ECCODESROOT/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<TEST_DIR>/run/awiesm//pi-awiesm-2.6.2/run_18500101-18500101/work//lib/fesom/
export USER=<USER_ACCOUNT>
export ACCOUNT=computing.computing
export ESM_TESTING_DIR=<TEST_DIR>/run/awiesm/
export MODEL_DIR=<TEST_DIR>/comp/awiesm/awiesm-2.6.2
export ENVIRONMENT_SET_BY_ESMTOOLS=TRUE

unset SLURM_MEM_PER_NODE
unset SLURM_MEM_PER_CPU

# Set stack size to unlimited
ulimit -s unlimited
# 3...2...1...Liftoff!

echo " $(date +"%Y-%m-%d %H:%M:%S.%3N") | PROGRESS | Tripy_Fesom_fesom 1 1850-01-01T00:00:00 45014450 - start" >> <TEST_DIR>/run/awiesm//pi-awiesm-2.6.2/log//pi-awiesm-2.6.2_awiesm.log

cd <TEST_DIR>/run/awiesm//pi-awiesm-2.6.2/run_18500101-18500101/work/
time srun -l --kill-on-bad-exit=1 --cpu_bind=cores <TEST_DIR>/run/awiesm//pi-awiesm-2.6.2/scripts/fesom/Subjob_tripy.sh <TEST_DIR>/run/awiesm//pi-awiesm-2.6.2/outdata/fesom/ 1850-01-01T00:00:00 1850-01-02T00:00:00 1850-01-01T00:00:00 1850-01-04T00:00:00 /albedo/pool/FESOM2//core2/ <TEST_DIR>/run/awiesm/ pi-awiesm-2.6.2 conda False NOT_SET NOT_SET 2>&1 &

wait
