comp:
        actual:
                files:
                    - "bin/pismr"
                    - "bin/vega_vip.x"
        check: {}
run:
        actual:
                errors:
                    - "MISSING FILES"
                    - "Traceback"
                files:
                    - "outdata/pism/*_pismr_extra_*.nc"
                    - "restart/pism/*_pismr_restart*.nc"
                    - "outdata/vilma/out/rsl.nc*"
                    - "outdata/vilma/vega.lis*"
                    - "restart/vilma/dflag.nc*"
                    - "restart/vilma/vega_deg1.dat*"
                    - "restart/vilma/vega_rpt.dat*"
                    - "restart/vilma/restart/ctc_stress.nc"
                    - "restart/vilma/restart/disp.nc"
                    - "restart/vilma/restart/mos_acompl.nc"
                    - "restart/vilma/restart/mos_acomp.nc"
                    - "restart/vilma/restart/mos_amtrx.nc"
                    - "restart/vilma/restart/mos_indx.nc"
                    - "restart/vilma/restart/pefgh.nc"
                    - "restart/vilma/restart/pjj.nc"
                    - "restart/vilma/restart/ve_struct.nc"
        check: {}
computers:
        - ollie
ignore_scripts:
        - vilma_test_run.yaml
        - pism-ollie-initial-yearly.yaml
